# Lecture slides {-}

<br/><small><a href="javascript:if(window.print)window.print()">Print this chapter</a></small>

This book is a companion for the module [GY7702 R for Data Science](https://le.ac.uk/modules/2021/gy7702) of the [MSc in Geographic Information Science](https://le.ac.uk/courses/geographical-information-science-msc/2021) at the [School of Geography, Geology, and the Environment](https://le.ac.uk/gge) of the [University of Leicester](https://le.ac.uk/). The module is composed of four units, each one two or three weeks long. Each Monday, I will publish three 20-minute lecture videos, along with the assigned reading, that will introduce you to the topics of the week. Please watch the lecture and then complete the reading before the practical sessions on Thursday. The practical session  will provide you the opportunity to apply what you have seen in the videos and read in the materials. The materials will include exercises that you will complete on your own time, after the practical session. If you have questions, please contact me via email or come along to office hours.

The slides used in the lectures are available as web-based slides at the pages linked below. 

1. **R coding**
    - **100 Introduction**
        - 101 [Introduction to R](slides/101-introduction.html)
        - 102 [Core concepts](slides/102-core-concepts.html)
        - 103 [Tidyverse](slides/103-tidyverse.html)
    - **110 R programming**
        - 111 [Data types (vectors, factors, matrices, arrays, lists)](slides/111-data-types.html)
        - 112 [Control structures (conditional statements, loops)](slides/112-control-structures.html)
        - 113 [Functions](slides/113-functions.html)
2. **Data wrangling**
    - **200 Selection and manipulation**
        - 201 [Data Frames](slides/201-data-frames.html)
        - 202 [Data selection and filtering](slides/202-selection-filtering.html)
        - 203 [Data manipulation](slides/203-data-manipulation.html)
    - **210 Table operations**
        - 211 [Join operations](slides/211-data-join.html)
        - 212 [Table pivot](slides/212-tidy-data.html)
        - 213 [Read and write data](slides/213-read-write.html)
    - **220 Reproducibility**
        - 221 [Reproducibility](slides/221-reproducibility.html)
        - 222 [R and Markdown](slides/222-rmarkdown.html)
        - 223 [Git](slides/223-git.html)
3. **Data analysis**
    - **300 Exploratory data analysis**
        - 301 [Data visualisation](slides/301-data-visualisation.html)
        - 302 [Descriptive statistics](slides/302-descriptive-stats.html)
        - 303 [Exploring assumptions](slides/303-exploring-assumptions.html)
    - **310 Comparing data** 
        - 311 [Comparing groups](slides/311-comparing-means.html)
        - 312 [Correlation](slides/312-correlation.html)
        - 313 [Data transformations](slides/313-data-transformations.html)
    - **320 Regression models**
        - 321 [Simple regression](slides/321-regression.html)
        - 322 [Multiple Regression](slides/322-regression-multiple.html)
        - 323 [Comparing regression models](slides/323-regression-comparing.html)
4. **Machine learning**
    - **400 Supervised**
        - 401 [Introduction to Machine Learning](slides/401-machine-learning-intro.html)
        - 402 [Artificial Neural Networks](slides/402-neural-networks.html)
        - 403 [Support vector machines](slides/403-support-vector-machines.html)
    - **410 Unsupervised**
        - 411 [Principal Component Analysis](slides/411-principal-components.html)
        - 412 [Centroid-based clustering](slides/412-clustering-centroid.html)
        - 413 [Hierarchical and density-based clustering](slides/413-clustering-hierarchical-density.html)


---

<small>by [Stefano De Sabbata](https://sdesabbata.github.io/) -- text licensed under the [CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/), contains public sector information licensed under the [Open Government Licence v3.0](http://www.nationalarchives.gov.uk/doc/open-government-licence), code licensed under the [GNU GPL v3.0](https://www.gnu.org/licenses/gpl-3.0.html).</small>