# # Install additional libraries

install.packages("here")
install.packages("car")
install.packages("caret")
install.packages("pastecs")
install.packages("psych")
install.packages("lm.beta")
install.packages("lmtest")
install.packages("gmodels")
install.packages("DescTools")
install.packages("dbscan")
install.packages("stargazer")
install.packages("skimr")
install.packages("ggmap")
install.packages("ggthemes")
install.packages("GGally")
install.packages("patchwork")
install.packages("factoextra")
install.packages("fmsb")
install.packages("palmerpenguins")
install.packages("neuralnet")
install.packages("kernlab")
install.packages("ROCR")
install.packages("pROC")
install.packages("xaringan")
install.packages("kableExtra")

# dev libs
install.packages("devtools")
devtools::install_github("hadley/emo")
devtools::install_github("r-lib/conflicted")
