<!DOCTYPE html>
<html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<title>Chapter 1 Introduction to R | R for Geographic Data Science</title>
<meta name="author" content="Stefano De Sabbata">
<meta name="description" content="This chapter is currently a draft. Print this chapter We start this chapter with a brief introduction to R, the programming language that will be the focus of the module, and the tool that we are...">
<meta name="generator" content="bookdown 0.24 with bs4_book()">
<meta property="og:title" content="Chapter 1 Introduction to R | R for Geographic Data Science">
<meta property="og:type" content="book">
<meta property="og:url" content="https://sdesabbata.github.io/r-for-geographic-data-science/introduction-to-r.html">
<meta property="og:image" content="https://sdesabbata.github.io/r-for-geographic-data-science/images/r-for-geographic-data-science-cover.png">
<meta property="og:description" content="This chapter is currently a draft. Print this chapter We start this chapter with a brief introduction to R, the programming language that will be the focus of the module, and the tool that we are...">
<meta name="twitter:card" content="summary">
<meta name="twitter:title" content="Chapter 1 Introduction to R | R for Geographic Data Science">
<meta name="twitter:description" content="This chapter is currently a draft. Print this chapter We start this chapter with a brief introduction to R, the programming language that will be the focus of the module, and the tool that we are...">
<meta name="twitter:image" content="https://sdesabbata.github.io/r-for-geographic-data-science/images/r-for-geographic-data-science-cover.png">
<!-- JS --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.6/clipboard.min.js" integrity="sha256-inc5kl9MA1hkeYUt+EC3BhlIgyp/2jDIyBLS6k3UxPI=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/fuse.js/6.4.6/fuse.js" integrity="sha512-zv6Ywkjyktsohkbp9bb45V6tEMoWhzFzXis+LrMehmJZZSys19Yxf1dopHx7WzIKxr5tK2dVcYmaCk2uqdjF4A==" crossorigin="anonymous"></script><script src="https://kit.fontawesome.com/6ecbd6c532.js" crossorigin="anonymous"></script><script src="libs/header-attrs-2.11/header-attrs.js"></script><script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script><meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link href="libs/bootstrap-4.6.0/bootstrap.min.css" rel="stylesheet">
<script src="libs/bootstrap-4.6.0/bootstrap.bundle.min.js"></script><script src="libs/bs3compat-0.3.1/transition.js"></script><script src="libs/bs3compat-0.3.1/tabs.js"></script><script src="libs/bs3compat-0.3.1/bs3compat.js"></script><link href="libs/bs4_book-1.0.0/bs4_book.css" rel="stylesheet">
<script src="libs/bs4_book-1.0.0/bs4_book.js"></script><!-- Global site tag (gtag.js) - Google Analytics --><script async src="https://www.googletagmanager.com/gtag/js?id=G-2Y0M0936JL"></script><script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'G-2Y0M0936JL');
    </script><script src="https://cdnjs.cloudflare.com/ajax/libs/autocomplete.js/0.38.0/autocomplete.jquery.min.js" integrity="sha512-GU9ayf+66Xx2TmpxqJpliWbT5PiGYxpaG8rfnBEk1LL8l1KGkRShhngwdXK1UgqhAzWpZHSiYPc09/NwDQIGyg==" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/mark.js/8.11.1/mark.min.js" integrity="sha512-5CYOlHXGh6QpOFA/TeTylKLWfB3ftPsde7AnmhuitiTX4K5SqCLBeKro6sPS8ilsz1Q4NRx3v8Ko2IBiszzdww==" crossorigin="anonymous"></script><!-- CSS --><link rel="stylesheet" href="style.css">
</head>
<body data-spy="scroll" data-target="#toc">

<div class="container-fluid">
<div class="row">
  <header class="col-sm-12 col-lg-3 sidebar sidebar-book"><a class="sr-only sr-only-focusable" href="#content">Skip to main content</a>

    <div class="d-flex align-items-start justify-content-between">
      <h1>
        <a href="index.html" title="">R for Geographic Data Science</a>
      </h1>
      <button class="btn btn-outline-primary d-lg-none ml-2 mt-1" type="button" data-toggle="collapse" data-target="#main-nav" aria-expanded="true" aria-controls="main-nav"><i class="fas fa-bars"></i><span class="sr-only">Show table of contents</span></button>
    </div>

    <div id="main-nav" class="collapse-lg">
      <form role="search">
        <input id="search" class="form-control" type="search" placeholder="Search" aria-label="Search">
</form>

      <nav aria-label="Table of contents"><h2>Table of contents</h2>
        <ul class="book-toc list-unstyled">
<li><a class="" href="index.html">Welcome</a></li>
<li class="book-part">Getting started</li>
<li><a class="active" href="introduction-to-r.html"><span class="header-section-number">1</span> Introduction to R</a></li>
<li><a class="" href="reproducible-data-science.html"><span class="header-section-number">2</span> Reproducible data science</a></li>
<li><a class="" href="data-manipulation.html"><span class="header-section-number">3</span> Data manipulation</a></li>
<li><a class="" href="table-operations.html"><span class="header-section-number">4</span> Table operations</a></li>
<li class="book-part">R scripting</li>
<li><a class="" href="control-structures.html"><span class="header-section-number">5</span> Control structures</a></li>
<li><a class="" href="working-with-functions.html"><span class="header-section-number">6</span> Working with functions</a></li>
<li class="book-part">Data analysis</li>
<li><a class="" href="exploratory-visualisation.html"><span class="header-section-number">7</span> Exploratory visualisation</a></li>
<li><a class="" href="exploratory-statistics.html"><span class="header-section-number">8</span> Exploratory statistics</a></li>
<li><a class="" href="comparing-data.html"><span class="header-section-number">9</span> Comparing data</a></li>
<li><a class="" href="regression-analysis.html"><span class="header-section-number">10</span> Regression analysis</a></li>
<li class="book-part">Machine learning</li>
<li><a class="" href="supervised-machine-learning.html"><span class="header-section-number">11</span> Supervised machine learning</a></li>
<li><a class="" href="unsupervised-machine-learning.html"><span class="header-section-number">12</span> Unsupervised machine learning</a></li>
<li class="book-part">Appendices</li>
<li><a class="" href="appendix-1.html">Appendix 1</a></li>
<li><a class="" href="solutions.html">Solutions</a></li>
<li><a class="" href="lecture-slides.html">Lecture slides</a></li>
<li><a class="" href="reading-list.html">Reading list</a></li>
<li><a class="" href="references.html">References</a></li>
</ul>

        <div class="book-extra">
          <p><a id="book-repo" href="https://github.com/sdesabbata/r-for-geographic-data-science">View book source <i class="fab fa-github"></i></a></p>
        </div>
      </nav>
</div>
  </header><main class="col-sm-12 col-md-9 col-lg-7" id="content"><div id="introduction-to-r" class="section level1" number="1">
<h1>
<span class="header-section-number">1</span> Introduction to R<a class="anchor" aria-label="anchor" href="#introduction-to-r"><i class="fas fa-link"></i></a>
</h1>
<p><br><small><em>This chapter is currently a draft.</em></small></p>
<p><br><small><a href="javascript:if(window.print)window.print()">Print this chapter</a></small></p>
<p>We start this chapter with a brief introduction to <code>R</code>, the programming language that will be the focus of the module, and the tool that we are going to use to do data science.</p>
<p><code>R</code> is one of the <a href="https://spectrum.ieee.org/top-programming-languages-2021#toggle-gdpr">most widely used programming languages nowadays</a>, along with Python, especially in geographic and satellite data science. I don’t personally have a strong preference for either, and I use both fairly regularly and in combination. Most of the time, using one or the other is a matter of habit or the availability of a particular functionality that makes it easier to complete the task you are set to do. For instance, Python has great libraries for programming deep neural networks. However, I find <code>R</code> more effective and powerful in data manipulation, statistical analysis, visualisation and mapping – which is the key reason why this book focuses on <code>R</code>. At the same time, beyond the mere details of syntax, the languages are not too different, and they are becoming easier to integrate. Most principles and approaches covered in this book can be applied when using Python, just using a different syntax.</p>
<div id="the-r-programming-language" class="section level2" number="1.1">
<h2>
<span class="header-section-number">1.1</span> The R programming language<a class="anchor" aria-label="anchor" href="#the-r-programming-language"><i class="fas fa-link"></i></a>
</h2>
<p><strong><a href="https://www.r-project.org/"><code>R</code></a></strong><span class="citation"><a class="footnote-ref" tabindex="0" data-toggle="popover" data-content='&lt;p&gt;&lt;a href="references.html#ref-R-base" role="doc-biblioref"&gt;R Core Team, &lt;em&gt;R&lt;/em&gt;&lt;/a&gt;.&lt;/p&gt;'><sup>4</sup></a></span> was created in 1992 by <code>R</code>oss Ihaka and Robert Gentleman at the University of Auckland, New Zealand. <code>R</code> is a free, open-source implementation of the <code>S</code> statistical programming language initially created at the Bell Labs. At its core, <code>R</code> is a functional programming language (its main functionalities revolve around defining and executing functions). However, it now supports and is commonly used as an imperative (focused on instructions on variables and programming control structures) and object-oriented (involving complex object structures) programming language.</p>
<p>In simple terms, nowadays, programming in <code>R</code> mainly focuses on devising a series of instructions to execute a task – most commonly, loading and analysing a dataset.</p>
<p>As such, R can be used to program by creating sequences of <strong>instructions</strong> involving <strong>variables</strong> – which are named entities that can store values, more on that below. That will be the main topic of this practical session. Instructions can include control flow structures, such as decision points (<em>if/else</em>) and loops, which will be the topic of the next practical session. Instructions can also be grouped into <strong>functions</strong>, which we will see in more detail in next chapter.</p>
<p><code>R</code> is <strong>interpreted</strong>, not compiled. This means that an <code>R</code> interpreter receives an instruction you write in <code>R</code>, interprets and executes them. Other programming languages require their code to be compiled in an executable to be executed on a computer.</p>
<div id="rstudio" class="section level3" number="1.1.1">
<h3>
<span class="header-section-number">1.1.1</span> RStudio<a class="anchor" aria-label="anchor" href="#rstudio"><i class="fas fa-link"></i></a>
</h3>
<p><a href="https://www.rstudio.com/">RStudio</a> is probably the most popular <a href="https://en.wikipedia.org/wiki/Integrated_development_environment">Integrated Development Environment (IDE)</a> for <code>R</code>. When using RStudio, the <code>R</code> interpreter is hidden in the backend, and RStudio is the frontend application that allows you to interact with the interpreter. As you open RStudio or RStudio Server, the interface is divided into two main sections. On the left side, you find the <em>Console</em> – and the <code>R</code> script editor, when a script is being edited. The <em>Console</em> in an input/output window into the <code>R</code> interpreter, where you can type instructions and see the resulting output.</p>
<p>For instance, if you type in the <em>Console</em></p>
<div class="sourceCode" id="cb6"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fl">1</span> <span class="op">+</span> <span class="fl">1</span></code></pre></div>
<p>the <code>R</code> interpreter understands that as an instruction to sum <code>1</code> to <code>1</code> and returns the following result as output.</p>
<pre><code>## [1] 2</code></pre>
<p>As these materials are created in RMarkdown, the output of the computation is always preceded by <code>##</code>. Note how the output value <code>2</code> is preceded by <code>[1]</code>, which indicates that the output is constituted by only one element. If the output is constituted by more than one element, as the list of numbers below, each row of the output is preceded by the index of the first element of the output.</p>
<pre><code>##  [1]   1   4   9  16  25  36  49  64  81 100 121 144 169 196 225 256 289 324 361
## [20] 400</code></pre>
<p>On the right side, you find two groups of panels. On the top-right, the main element is the <em>Environment</em> panel, which represents of the current state of the interpreter’s memory, showing all the information available for computation. For instance, that is where you will be able to see datasets loaded for analysis. On the bottom-right, you find the <em>Files</em> panel, which shows the file system (file and folders on your computer or the server), as well as the <em>Help</em> panel, which shows you the help pages when required. We will discuss the other panels later on in the practical sessions.</p>
</div>
<div id="coding-style" class="section level3" number="1.1.2">
<h3>
<span class="header-section-number">1.1.2</span> Coding style<a class="anchor" aria-label="anchor" href="#coding-style"><i class="fas fa-link"></i></a>
</h3>
<p>A coding style is a set of rules and guidelines to write programming code designed to ensure that the code is easy to read, understand, and consistent over time. Following a good coding style is essential when writing code that others will read – for instance, if you work in a team, publish your code or submit your code as a piece of coursework – and it ensures you will understand your code in a few months. Following a good coding style is also an essential step towards reproducibility, as we will see in a later chapter.</p>
<p>In this book, I will follow the <a href="http://style.tidyverse.org/">Tidyverse Style Guide (style.tidyverse.org)</a>. Study the Tidyverse Style Guide and use it consistently.</p>
</div>
</div>
<div id="core-concepts" class="section level2" number="1.2">
<h2>
<span class="header-section-number">1.2</span> Core concepts<a class="anchor" aria-label="anchor" href="#core-concepts"><i class="fas fa-link"></i></a>
</h2>
<div id="values" class="section level3" number="1.2.1">
<h3>
<span class="header-section-number">1.2.1</span> Values<a class="anchor" aria-label="anchor" href="#values"><i class="fas fa-link"></i></a>
</h3>
<p>When a value is typed in the <em>Console</em>, the interpreter returns the same value. In the examples below, <code>2</code> is a simple numeric value, while <code>"String value"</code> is a textual value, which in <code>R</code> is referred to as a <em>character</em> value and in programming is also commonly referred to as a <em>string</em> (short for <em>a string of characters</em>).</p>
<p>Numeric example:</p>
<div class="sourceCode" id="cb9"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fl">2</span></code></pre></div>
<pre><code>## [1] 2</code></pre>
<p>Character example:</p>
<div class="sourceCode" id="cb11"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="st">"String value"</span></code></pre></div>
<pre><code>## [1] "String value"</code></pre>
<p>Note how character values need to start and end with a single or double quote (<code>'</code> or <code>"</code>), which are not part of the information themselves. The <a href="https://style.tidyverse.org/syntax.html">Tidyverse Style Guide</a> suggests always using the double quote (<code>"</code>), so we will use those in this module.</p>
<p>Anything that follows a <code>#</code> symbol is considered a <em>comment</em>, and the interpreter ignores it.</p>
<div class="sourceCode" id="cb13"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># hi, I am a comment, please ignore me</span></code></pre></div>
<p>As mentioned above, the interpreter understands <a href="https://stat.ethz.ch/R-manual/R-devel/library/base/html/Arithmetic.html">simple operations on numeric values</a>, as we discuss in more detail below.</p>
<div class="sourceCode" id="cb14"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fl">1</span> <span class="op">+</span> <span class="fl">1</span></code></pre></div>
<pre><code>## [1] 2</code></pre>
</div>
<div id="variables" class="section level3" number="1.2.2">
<h3>
<span class="header-section-number">1.2.2</span> Variables<a class="anchor" aria-label="anchor" href="#variables"><i class="fas fa-link"></i></a>
</h3>
<p>In computer programming, a <strong>variable</strong> can be thought about as a storage location (a bit of memory) with an associated name (also referred to as identifier) and a value that can vary – hence the name variable. When programming, you can define a variable by naming it with an <strong>identifier</strong> and providing a <strong>value</strong> to be stored in the variable. After that, you can retrieve the value stored in the variable by specifying the chosen identifier. Variables are an essential tool in programming, as they allow to save the result of a piece of computation and to retrieve it later on for further analysis.</p>
<p>A variable can be defined in <code>R</code> using an identifier (e.g., <code>a_variable</code>) on the left of an <strong>assignment operator</strong> <code><a href="https://rdrr.io/r/base/assignOps.html">&lt;-</a></code>, followed by the object to be linked to the identifier, such as a value (e.g., <code>1</code>) to be assigned on the right. The value of the variable can be invoked by simply specifying the identifier.</p>
<div class="sourceCode" id="cb16"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">a_variable</span> <span class="op">&lt;-</span> <span class="fl">1</span>
<span class="va">a_variable</span></code></pre></div>
<pre><code>## [1] 1</code></pre>
<p>If you type <code>a_variable &lt;- 1</code> in the <em>Console</em> in RStudio, a new element appears in the <em>Environment</em> panel, representing the new variable in the memory. The left part of the entry contains the identifier <code>a_variable</code>, and the right part contains the value assigned to the variable <code>a_variable</code>, that is <code>1</code>. In the example below, another variable named <code>another_variable</code> is created and summed to <code>a_variable</code>, saving the result in <code>sum_of_two_variables</code>.</p>
<div class="sourceCode" id="cb18"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">another_variable</span> <span class="op">&lt;-</span> <span class="fl">4</span>
<span class="va">another_variable</span></code></pre></div>
<pre><code>## [1] 4</code></pre>
<div class="sourceCode" id="cb20"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">sum_of_two_variables</span> <span class="op">&lt;-</span> <span class="va">a_variable</span> <span class="op">+</span> <span class="va">another_variable</span>
<span class="va">sum_of_two_variables</span></code></pre></div>
<pre><code>## [1] 5</code></pre>
</div>
<div id="data-frames" class="section level3" number="1.2.3">
<h3>
<span class="header-section-number">1.2.3</span> Data frames<a class="anchor" aria-label="anchor" href="#data-frames"><i class="fas fa-link"></i></a>
</h3>
<p><em>to-do: incl tibbles</em></p>
</div>
<div id="algorithms" class="section level3" number="1.2.4">
<h3>
<span class="header-section-number">1.2.4</span> Algorithms<a class="anchor" aria-label="anchor" href="#algorithms"><i class="fas fa-link"></i></a>
</h3>
<p>Any operation that can be executed using a computer is called an <strong>algorithm</strong>. To be more precise, <span class="citation"><a href="references.html#ref-cutland_1980" role="doc-biblioref">Nigel Cutland</a><a class="footnote-ref" tabindex="0" data-toggle="popover" data-content='&lt;p&gt;&lt;a href="references.html#ref-cutland_1980" role="doc-biblioref"&gt;&lt;em&gt;Computability: An Introduction to Recursive Function Theory&lt;/em&gt; (Cambridge University Press, 1980), &lt;/a&gt;&lt;a href="https://doi.org/10.1017/CBO9781139171496" role="doc-biblioref"&gt;https://doi.org/10.1017/CBO9781139171496&lt;/a&gt;.&lt;/p&gt;'><sup>5</sup></a></span> defined an algorithm as <em>“a mechanical rule, or automatic method, or program for performing some mathematical operation”</em> (Cutland, 1980, p. 7<span class="citation"><a class="footnote-ref" tabindex="0" data-toggle="popover" data-content='&lt;p&gt;&lt;a href="references.html#ref-cutland_1980" role="doc-biblioref"&gt;Cutland&lt;/a&gt;.&lt;/p&gt;'><sup>6</sup></a></span>).</p>
<p>The instructions you get to mount your Ikea furniture can be thought of as an algorithm, an effective procedure to perform the operation of mounting your furniture. You are playing the part of the computer executing the algorithm.</p>
<p>A <strong>program</strong> is a set of instructions implementing an abstract algorithm into a specific language – let that be R, Python, or any other language. In their definition, algorithms (and thus the programs that implement them) can use variables and functions. As is the case for <code>R</code>, programs that are interpreted rather than compiled are also referred to as <strong>scripts</strong>.</p>
</div>
<div id="functions" class="section level3" number="1.2.5">
<h3>
<span class="header-section-number">1.2.5</span> Functions<a class="anchor" aria-label="anchor" href="#functions"><i class="fas fa-link"></i></a>
</h3>
<p>You can think of a <strong>function</strong> as a processing unit that, having received some values as input, performs a specific task and can return a value as output. Some simple algorithms can be coded as programs made of only one function that performs the whole task. More complex algorithms might require multiple functions, each designed to complete a sub-task, which combined perform the entire task.</p>
<p>You can <strong>invoke</strong> a function by specifying the <strong>function name</strong> along with the <strong>arguments</strong> (input values) between simple brackets. Each argument corresponds to a <strong>parameter</strong> (i.e., an internal variable used within the function to run the operation, as we will see in more detail later in this book). Programming languages provide pre-defined functions that implement common algorithms (e.g., finding the square root of a number or calculating a linear regression).</p>
<p>For instance, <code>sqrt</code> is the pre-defined function in <code>R</code> that computes the square root of a number. The instruction <code><a href="https://rdrr.io/r/base/MathFun.html">sqrt(2)</a></code> tells the <code>R</code> interpreter to run the function that calculates the square root using <code>2</code> as the input value. The function will return <code>1.414214</code>, the square root of <code>2</code>, as the output.</p>
<div class="sourceCode" id="cb22"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/base/MathFun.html">sqrt</a></span><span class="op">(</span><span class="fl">2</span><span class="op">)</span></code></pre></div>
<pre><code>## [1] 1.414214</code></pre>
<p>Another example is the function <code>round</code>, which returns a value rounded to a specified number of digits after the dot. For instance, <code><a href="https://rdrr.io/r/base/Round.html">round(1.414214, digits = 2)</a></code> returns <code>1.41</code>. In this case, we specify that the second argument refers to the number of digits to be kept, and this is because this function also has other arguments that can be specified.</p>
<div class="sourceCode" id="cb24"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span><span class="fl">1.414214</span>, digits <span class="op">=</span> <span class="fl">2</span><span class="op">)</span></code></pre></div>
<pre><code>## [1] 1.41</code></pre>
<p>Functions can also be used on the right side of the assignment operator <code><a href="https://rdrr.io/r/base/assignOps.html">&lt;-</a></code> in which case the output value of the function will be stored in the memory slot with that identifier. Variables can be used as arguments. For instance, after saving the result of the square root of two in the variable <code>sqrt_of_two</code>, we can use the same variable as the first argument for the function <code>round</code>.</p>
<div class="sourceCode" id="cb26"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">sqrt_of_two</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/MathFun.html">sqrt</a></span><span class="op">(</span><span class="fl">2</span><span class="op">)</span>
<span class="va">sqrt_of_two</span></code></pre></div>
<pre><code>## [1] 1.414214</code></pre>
<div class="sourceCode" id="cb28"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span><span class="va">sqrt_of_two</span>, digits <span class="op">=</span> <span class="fl">2</span><span class="op">)</span></code></pre></div>
<pre><code>## [1] 1.41</code></pre>
<p>Functions can also be used as arguments of functions. Instead of first calculating the square root of two, saving the value in a variable, and then using the variable as the first argument of <code>round</code>, we can directly add the function <code>sqrt</code> and its argument as the first argument of the function <code>round</code>.</p>
<div class="sourceCode" id="cb30"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/MathFun.html">sqrt</a></span><span class="op">(</span><span class="fl">2</span><span class="op">)</span>, digits <span class="op">=</span> <span class="fl">2</span><span class="op">)</span></code></pre></div>
<pre><code>## [1] 1.41</code></pre>
<p>In the next chapter, we will see how you can create functions yourself.</p>
<p>As we introduce variables and functions, and functions using variables and functions, the complexity of our code increases quite rapidly. In fact, using a function as the argument for another function is usually discouraged because it makes the code more difficult to read. Instead, it would be best to always aim for a code that is as easy to read and understand as possible. An essential step in ensuring that is to follow coding style guidelines closely.</p>
</div>
<div id="libraries" class="section level3" number="1.2.6">
<h3>
<span class="header-section-number">1.2.6</span> Libraries<a class="anchor" aria-label="anchor" href="#libraries"><i class="fas fa-link"></i></a>
</h3>
<p>Functions can be collected and stored in <em>libraries</em> (sometimes referred to as <em>packages</em>), containing related functions and sometimes datasets. For instance, the <code>base</code> library in <code>R</code> includes the <code>sqrt</code> function above, and the <code>rgdal</code> library, which contains implementations of the <a href="https://gdal.org/">GDAL (Geospatial Data Abstraction Library)</a> functionalities for <code>R</code>.</p>
<p>Libraries can be installed in <code>R</code> using the function <code>install.packages</code> or using <code>Tool &gt; Install Packages...</code> in RStudio.</p>
</div>
</div>
<div id="tidyverse" class="section level2" number="1.3">
<h2>
<span class="header-section-number">1.3</span> Tidyverse<a class="anchor" aria-label="anchor" href="#tidyverse"><i class="fas fa-link"></i></a>
</h2>
<p>The meta-library <a href="https://www.tidyverse.org/">Tidyverse</a><span class="citation"><a class="footnote-ref" tabindex="0" data-toggle="popover" data-content='&lt;p&gt;&lt;a href="references.html#ref-tidyverse2019" role="doc-biblioref"&gt;Hadley Wickham et al., &lt;span&gt;“Welcome to the &lt;span class="nocase"&gt;tidyverse&lt;/span&gt;,”&lt;/span&gt; &lt;em&gt;Journal of Open Source Software&lt;/em&gt; 4, no. 43 (2019): 1686, &lt;/a&gt;&lt;a href="https://doi.org/10.21105/joss.01686" role="doc-biblioref"&gt;https://doi.org/10.21105/joss.01686&lt;/a&gt;.&lt;/p&gt;'><sup>7</sup></a></span> contains the following libraries:</p>
<ul>
<li>
<a href="https://ggplot2.tidyverse.org/"><code>ggplot2</code></a><span class="citation"><a class="footnote-ref" tabindex="0" data-toggle="popover" data-content='&lt;p&gt;&lt;a href="references.html#ref-ggplot2" role="doc-biblioref"&gt;Hadley Wickham, &lt;em&gt;Ggplot2: Elegant Graphics for Data Analysis&lt;/em&gt; (Springer-Verlag New York, 2016), &lt;/a&gt;&lt;a href="https://ggplot2.tidyverse.org" role="doc-biblioref"&gt;https://ggplot2.tidyverse.org&lt;/a&gt;.&lt;/p&gt;'><sup>8</sup></a></span> is a system for declaratively creating graphics based on The Grammar of Graphics. You provide the data, tell ggplot2 how to map variables to aesthetics, what graphical primitives to use, and it takes care of the details.</li>
<li>
<a href="https://dplyr.tidyverse.org/"><code>dplyr</code></a> provides a grammar of data manipulation, providing a consistent set of verbs that solve the most common data manipulation challenges.</li>
<li>
<a href="https://tidyr.tidyverse.org/"><code>tidyr</code></a> provides a set of functions that help you get to tidy data. Tidy data is data with a consistent form: in brief, every variable goes in a column, and every column is a variable.</li>
<li>
<a href="https://readr.tidyverse.org/"><code>readr</code></a> provides a fast and friendly way to read rectangular data (like csv, tsv, and fwf). It is designed to flexibly parse many types of data found in the wild, while still cleanly failing when data unexpectedly changes.</li>
<li>
<a href="https://purrr.tidyverse.org/"><code>purrr</code></a> enhances <code>R</code>’s functional programming (FP) toolkit by providing a complete and consistent set of tools for working with functions and vectors. Once you master the basic concepts, purrr allows you to replace many for loops with code that is easier to write and more expressive.</li>
<li>
<a href="https://tibble.tidyverse.org/"><code>tibble</code></a> is a modern re-imagining of the data frame, keeping what time has proven to be effective, and throwing out what it has not. Tibbles are data.frames that are lazy and surly: they do less and complain more forcing you to confront problems earlier, typically leading to cleaner, more expressive code.</li>
<li>
<a href="https://stringr.tidyverse.org/"><code>stringr</code></a> provides a cohesive set of functions designed to make working with strings as easy as possible. It is built on top of stringi, which uses the ICU C library to provide fast, correct implementations of common string manipulations.</li>
<li>
<a href="https://forcats.tidyverse.org/"><code>forcats</code></a> provides a suite of useful tools that solve common problems with factors. <code>R</code> uses factors to handle categorical variables, variables that have a fixed and known set of possible values.</li>
</ul>
<p>A library can be loaded using the function <code>library</code>, as shown below (note the name of the library is not quoted). Once a library is installed on a computer, you don’t need to install it again, but every script needs to load all the libraries that it uses. Once a library is loaded, all its functions can be used.</p>
<p><strong>Important</strong>: it is always necessary to load the <code>tidyverse</code> meta-library if you want to use the <code>stringr</code> functions or the pipe operator <code>%&gt;%</code>.</p>
<div class="sourceCode" id="cb32"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://tidyverse.tidyverse.org">tidyverse</a></span><span class="op">)</span></code></pre></div>
<!--
### stringr

The code below presents the same examples used in the lecture session to demonstrate the use of `stringr` functions.


```r
str_length("Leicester")
```

```
## [1] 9
```

```r
str_detect("Leicester", "e")
```

```
## [1] TRUE
```

```r
str_replace_all("Leicester", "e", "x")
```

```
## [1] "Lxicxstxr"
```
-->
<div id="the-pipe-operator" class="section level3" number="1.3.1">
<h3>
<span class="header-section-number">1.3.1</span> The pipe operator<a class="anchor" aria-label="anchor" href="#the-pipe-operator"><i class="fas fa-link"></i></a>
</h3>
<p>The pipe operator is useful to outline more complex operations, step by step (see also <a href="https://r4ds.had.co.nz/pipes.html">R for Data Science, Chapter 18</a>). The pipe operator <code>%&gt;%</code></p>
<ul>
<li>takes the result from one function</li>
<li>and passes it to the next function</li>
<li>as the <strong>first argument</strong>
</li>
<li>that doesn’t need to be included in the code anymore</li>
</ul>
<p>The code below shows a simple example. The number <code>2</code> is taken as input for the first pipe that passes it on as the first argument to the function <code>sqrt</code>. The output value <code>1.41</code> is then taken as input for the second pipe, which passes it on as the first argument to the function <code>trunc</code>. The final output <code>1</code> is finally returned.</p>
<div class="sourceCode" id="cb33"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fl">2</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://rdrr.io/r/base/MathFun.html">sqrt</a></span><span class="op">(</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://rdrr.io/r/base/Round.html">trunc</a></span><span class="op">(</span><span class="op">)</span></code></pre></div>
<pre><code>## [1] 1</code></pre>
<p>The image below graphically illustrates how the pipe operator works, compared to the same procedure executed using two temporary variables that are used to store temporary values.</p>
<center>
<div class="figure">
<img src="images/PipeOperator.png" style="width:80.0%" alt=""><p class="caption">Illustration of how the pipe operator works</p>
</div>
</center>
<div class="sourceCode" id="cb35"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/base/MathFun.html">sqrt</a></span><span class="op">(</span><span class="fl">2</span><span class="op">)</span> <span class="op">%&gt;%</span>
 <span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span>digits <span class="op">=</span> <span class="fl">2</span><span class="op">)</span></code></pre></div>
<p>The first step of a sequence of pipes can be a value, a variable, or a function, including arguments. The code below shows a series of examples of different ways of achieving the same result. The examples use the function <code>round</code>, which also allows for a second argument: <code>digits = 2</code>. Note that, when using the pipe operator, only the nominally second argument is provided to the function <code>round</code> – that is <code><a href="https://rdrr.io/r/base/Round.html">round(digits = 2)</a></code></p>
<div class="sourceCode" id="cb36"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># No pipe, using variables</span>
<span class="va">tmp_variable_A</span> <span class="op">&lt;-</span> <span class="fl">2</span>
<span class="va">tmp_variable_B</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/MathFun.html">sqrt</a></span><span class="op">(</span><span class="va">tmp_variable_A</span><span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span><span class="va">tmp_variable_B</span>, digits <span class="op">=</span> <span class="fl">2</span><span class="op">)</span>

<span class="co"># No pipe, using functions only</span>
<span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/MathFun.html">sqrt</a></span><span class="op">(</span><span class="fl">2</span><span class="op">)</span>, digits <span class="op">=</span> <span class="fl">2</span><span class="op">)</span>

<span class="co"># Pipe starting from a value</span>
<span class="fl">2</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://rdrr.io/r/base/MathFun.html">sqrt</a></span><span class="op">(</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span>digits <span class="op">=</span> <span class="fl">2</span><span class="op">)</span>

<span class="co"># Pipe starting from a variable</span>
<span class="va">the_value_two</span> <span class="op">&lt;-</span> <span class="fl">2</span>
<span class="va">the_value_two</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://rdrr.io/r/base/MathFun.html">sqrt</a></span><span class="op">(</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span>digits <span class="op">=</span> <span class="fl">2</span><span class="op">)</span>

<span class="co"># Pipe starting from a function</span>
<span class="fu"><a href="https://rdrr.io/r/base/MathFun.html">sqrt</a></span><span class="op">(</span><span class="fl">2</span><span class="op">)</span> <span class="op">%&gt;%</span>
 <span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span>digits <span class="op">=</span> <span class="fl">2</span><span class="op">)</span></code></pre></div>
<p>A complex operation created through the use of <code>%&gt;%</code> can be used on the right side of <code><a href="https://rdrr.io/r/base/assignOps.html">&lt;-</a></code>, to assign the outcome of the operation to a variable.</p>
<div class="sourceCode" id="cb37"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">sqrt_of_two</span> <span class="op">&lt;-</span> <span class="fl">2</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://rdrr.io/r/base/MathFun.html">sqrt</a></span><span class="op">(</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span>digits <span class="op">=</span> <span class="fl">2</span><span class="op">)</span></code></pre></div>
</div>
</div>
<div id="exercise-104.1" class="section level2" number="1.4">
<h2>
<span class="header-section-number">1.4</span> Exercise 104.1<a class="anchor" aria-label="anchor" href="#exercise-104.1"><i class="fas fa-link"></i></a>
</h2>
<p><strong>Question 104.1.1:</strong> Write a piece of code using the pipe operator that takes as input the number <code>1632</code>, calculates the logarithm to the base 10, takes the highest integer number lower than the calculated value (lower round), and verifies whether it is an integer.</p>
<p><strong>Question 104.1.2:</strong> Write a piece of code using the pipe operator that takes as input the number <code>1632</code>, calculates the square root, takes the lowest integer number higher than the calculated value (higher round), and verifies whether it is an integer.</p>
<p><strong>Question 104.1.3:</strong> Write a piece of code using the pipe operator that takes as input the string <code>"1632"</code>, transforms it into a number, and checks whether the result is <em>Not a Number</em>.</p>
<p><strong>Question 104.1.4:</strong> Write a piece of code using the pipe operator that takes as input the string <code>"-16.32"</code>, transforms it into a number, takes the absolute value and truncates it, and finally checks whether the result is <em>Not Available</em>.</p>
</div>
<div id="exercise-104.2" class="section level2" number="1.5">
<h2>
<span class="header-section-number">1.5</span> Exercise 104.2<a class="anchor" aria-label="anchor" href="#exercise-104.2"><i class="fas fa-link"></i></a>
</h2>
<p><em>to-do: exercise with data frames</em></p>
<!--

Answer the question below, consulting the [`stringr` library reference (stringr.tidyverse.org/reference)](https://stringr.tidyverse.org/reference/index.html) as necessary

**Question 104.2.1:** Write a piece of code using the pipe operator and the `stringr` library that takes as input the string `"I like programming in R"`, and transforms it all in uppercase.

**Question 104.2.2:** Write a piece of code using the pipe operator and the `stringr` library that takes as input the string `"I like programming in R"`, and truncates it, leaving only 10 characters.

**Question 104.2.3:** Write a piece of code using the pipe operator and the `stringr` library that takes as input the string `"I like programming in R"`, and truncates it, leaving only 10 characters and using no ellipsis.

**Question 104.2.4:** Write a piece of code using the pipe operator and the `stringr` library that takes as input the string `"I like programming in R"`, and manipulates to leave only the string `"I like R"`.

-->
<hr>
<p><small>by <a href="https://sdesabbata.github.io/">Stefano De Sabbata</a> – text licensed under the <a href="https://creativecommons.org/licenses/by-sa/4.0/">CC BY-SA 4.0</a>, contains public sector information licensed under the <a href="http://www.nationalarchives.gov.uk/doc/open-government-licence">Open Government Licence v3.0</a>, code licensed under the <a href="https://www.gnu.org/licenses/gpl-3.0.html">GNU GPL v3.0</a>.</small></p>

</div>
</div>

  <div class="chapter-nav">
<div class="prev"><a href="index.html">Welcome</a></div>
<div class="next"><a href="reproducible-data-science.html"><span class="header-section-number">2</span> Reproducible data science</a></div>
</div></main><div class="col-md-3 col-lg-2 d-none d-md-block sidebar sidebar-chapter">
    <nav id="toc" data-toggle="toc" aria-label="On this page"><h2>On this page</h2>
      <ul class="nav navbar-nav">
<li><a class="nav-link" href="#introduction-to-r"><span class="header-section-number">1</span> Introduction to R</a></li>
<li>
<a class="nav-link" href="#the-r-programming-language"><span class="header-section-number">1.1</span> The R programming language</a><ul class="nav navbar-nav">
<li><a class="nav-link" href="#rstudio"><span class="header-section-number">1.1.1</span> RStudio</a></li>
<li><a class="nav-link" href="#coding-style"><span class="header-section-number">1.1.2</span> Coding style</a></li>
</ul>
</li>
<li>
<a class="nav-link" href="#core-concepts"><span class="header-section-number">1.2</span> Core concepts</a><ul class="nav navbar-nav">
<li><a class="nav-link" href="#values"><span class="header-section-number">1.2.1</span> Values</a></li>
<li><a class="nav-link" href="#variables"><span class="header-section-number">1.2.2</span> Variables</a></li>
<li><a class="nav-link" href="#data-frames"><span class="header-section-number">1.2.3</span> Data frames</a></li>
<li><a class="nav-link" href="#algorithms"><span class="header-section-number">1.2.4</span> Algorithms</a></li>
<li><a class="nav-link" href="#functions"><span class="header-section-number">1.2.5</span> Functions</a></li>
<li><a class="nav-link" href="#libraries"><span class="header-section-number">1.2.6</span> Libraries</a></li>
</ul>
</li>
<li>
<a class="nav-link" href="#tidyverse"><span class="header-section-number">1.3</span> Tidyverse</a><ul class="nav navbar-nav"><li><a class="nav-link" href="#the-pipe-operator"><span class="header-section-number">1.3.1</span> The pipe operator</a></li></ul>
</li>
<li><a class="nav-link" href="#exercise-104.1"><span class="header-section-number">1.4</span> Exercise 104.1</a></li>
<li><a class="nav-link" href="#exercise-104.2"><span class="header-section-number">1.5</span> Exercise 104.2</a></li>
</ul>

      <div class="book-extra">
        <ul class="list-unstyled">
<li><a id="book-source" href="https://github.com/sdesabbata/r-for-geographic-data-science/blob/main/src/book/101-Introduction.Rmd">View source <i class="fab fa-github"></i></a></li>
          <li><a id="book-edit" href="https://github.com/sdesabbata/r-for-geographic-data-science/edit/main/src/book/101-Introduction.Rmd">Edit this page <i class="fab fa-github"></i></a></li>
        </ul>
</div>
    </nav>
</div>

</div>
</div> <!-- .container -->

<footer class="bg-primary text-light mt-5"><div class="container"><div class="row">

  <div class="col-12 col-md-6 mt-3">
    <p>"<strong>R for Geographic Data Science</strong>" was written by Stefano De Sabbata. It was last built on 2022-09-24.</p>
  </div>

  <div class="col-12 col-md-6 mt-3">
    <p>This book was built by the <a class="text-light" href="https://bookdown.org">bookdown</a> R package.</p>
  </div>

</div></div>
</footer><!-- dynamically load mathjax for compatibility with self-contained --><script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script><script type="text/x-mathjax-config">const popovers = document.querySelectorAll('a.footnote-ref[data-toggle="popover"]');
for (let popover of popovers) {
  const div = document.createElement('div');
  div.setAttribute('style', 'position: absolute; top: 0, left:0; width:0, height:0, overflow: hidden; visibility: hidden;');
  div.innerHTML = popover.getAttribute('data-content');

  var has_math = div.querySelector("span.math");
  if (has_math) {
    document.body.appendChild(div);
    MathJax.Hub.Queue(["Typeset", MathJax.Hub, div]);
    MathJax.Hub.Queue(function() {
      popover.setAttribute('data-content', div.innerHTML);
      document.body.removeChild(div);
    })
  }
}
</script>
</body>
</html>
